### ISSUE TITLE
`create_clickcollect_overview.py` crashing due to attribute error

### ISSUE THREAD

**Issue by muety** [leih-lokal/scripts#14]
Got the following error message in Windows 10, Python 3.11, Pandas 2.0.3:

```
C:\Users\leihlokal\Desktop\scripts\create_clickcollect_overview.py:184: DtypeWarning: Columns (7,26,28,30,31,33,37,38,39,40,42,43,47,48,49,50,52,56,57,58,59,61,65,66,67,68,70,74,75,76,77,79,83,84,85,86,88,92,93,94,95,97,101,102,103,104,106,110,111,112,113,115,119,120,121,122,124,125,126,127,128,129,133,134,135,136,138,142,143,144,145,149) have mixed types. Specify dtype option on import or set low_memory=False.
df = pd.read_csv(f, sep=';')
Traceback (most recent call last):
File "C:\Users\leihlokal\Desktop\scripts\create_clickcollect_overview.py", line 272, in <module>
df_selected = df_selected.append([{'Zeit': s} for s in missing_slots], ignore_index=True)
^^^^^^^^^^^^^^^^^^
File "C:\Users\leihlokal\AppData\Roaming\Python\Python311\site-packages\pandas\core\generic.py", line 5989, in __getattr__
return object.__getattribute__(self, name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```

(Formatting is messed up, sorry)

**Comment by skjerns** [comment]
Ah, yes, `append` has been depricated

**Comment by skjerns** [comment]
I fixed it in https://github.com/leih-lokal/scripts/commit/a49681a0d449a3759cad6650529f8c14b0ee592b

Can you pull the changes and confirm that it works (can't test it here)

**Comment by muety** [comment]
That was quick! Will test on Thursday.

**Comment by muety** [comment]
Parantheses are messed up in line 272. And I got another error: 

```
Traceback (most recent call last):                                                                                        File "C:\Users\leihlokal\Desktop\scripts\create_clickcollect_overview.py", line 322, in <module>                          sheet.set_column(f'{char}:{char}', sheet.col_sizes[i][0], format)                                                                                          ^^^^^^^^^^^^^^^                                                                  AttributeError: 'Worksheet' object has no attribute 'col_sizes'. Did you mean: 'row_sizes'?
```

**Comment by skjerns** [comment]
I'm back home, can check it later

**Comment by muety** [comment]
`col_sizes` is used once more in line 328. But apart from that, seems to be working. Didn't yet check the file's content, though.

Also, we might want to use just `start {xlsx_file}` instead of `start excel.exe {xlsx_file}` to prevent the script from crashing on systems where LibreOffice is used instead of Excel.

**Comment by skjerns** [comment]
> `col_sizes` is used once more in line 328. But apart from that, seems to be working. Didn't yet check the file's content, though.
> 
> Also, we might want to use just `start {xlsx_file}` instead of `start excel.exe {xlsx_file}` to prevent the script from crashing on systems where LibreOffice is used instead of Excel.

sure, feel free to change that and commit!
